jobs:
  combine-prs:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: combine-prs
      name: combine-prs
      uses: github/combine-prs@v5.0.0
      with:
        branch_regex: ^(dependa|wrapper)bot\/.*$
name: Combine PRs
on:
  repository_dispatch:
    types: trigger-ga___combine-prs.yml
permissions:
  checks: read
  contents: write
  pull-requests: write
