jobs:
  validation:
    name: Validation
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: gradle/actions/wrapper-validation@v3
name: Validate Gradle Wrapper
on:
  repository_dispatch:
    types: trigger-ga___gradle-wrapper-validation.yml
