jobs:
  comment:
    if: github.repository_owner == 'testng-team'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Label Commenter
      uses: peaceiris/actions-label-commenter@v1
name: Label Commenter
on:
  repository_dispatch:
    types: trigger-ga___label-commenter.yml
permissions:
  contents: read
  issues: write
