jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Gradle wrapper validation
      uses: gradle/actions/wrapper-validation@v3
    - continue-on-error: true
      name: Publish to GitHub
      run: './gradlew -PghNexusUsername=${{ secrets.NEXUS_USERNAME }} -PghNexusPassword=${{
        secrets.NEXUS_PASSWORD }} -Pgh publish

        '
name: Publish Snapshot
on:
  repository_dispatch:
    types: trigger-ga___publish-snapshot.yml
