jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Gradle wrapper validation
      uses: gradle/actions/wrapper-validation@v3
    - continue-on-error: true
      env:
        ORG_GRADLE_PROJECT_ghGitSourcePassword: ${{ secrets.GITHUB_TOKEN }}
        ORG_GRADLE_PROJECT_ghGitSourceUsername: ${{ github.actor }}
        ORG_GRADLE_PROJECT_ghNexusPassword: ${{ secrets.NEXUS_PASSWORD }}
        ORG_GRADLE_PROJECT_ghNexusUsername: ${{ secrets.NEXUS_USERNAME }}
        ORG_GRADLE_PROJECT_rc: ${{ github.event.inputs.release_candidate }}
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
        ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.GPG_KEY_ID }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSPHRASE }}
      name: Publish Release Candidate
      run: './gradlew -PghDryRun prepareVote

        '
    - continue-on-error: true
      name: Display next step
      run: 'echo "Now run ''release-maven-central.yml'' workflow using the same Release
        Candidate Number (rc #)"

        '
name: Publish to Maven Central
on:
  repository_dispatch:
    types: trigger-ga___publish-maven-central.yml
