jobs:
  update-gradle-wrapper:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Update Gradle Wrapper
      uses: gradle-update/update-gradle-wrapper-action@v1
name: Update Gradle Wrapper
on:
  repository_dispatch:
    types: trigger-ga___update-gradle-wrapper.yml
